export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const UPDATE_USER_AUTH = "UPDATE_USER_AUTH"
export const GET_PORTFOLIOS = "GET_PORTFOLIOS"
export const UPDATE_PORTFOLIOS = "UPDATE_PORTFOLIOS"